### ISSUE TITLE
"App not installed"

### ISSUE THREAD

**Issue by codingatty** [USPTO/TrademarkStatusApp#1]
I receive the error message "There was a problem parsing the package" trying to install the APK for the Android app. The APK was obtained from https://github.com/USPTO/TrademarkStatusApp/blob/master/app/releases/android-release-unsigned.apk on November 16 2016.

The same error occurs on two different Android devices; one phone and one tablet. Both devices  allow for installation from "unknown sources" (i.e., from sources other than the Google Play Store). I've installed other APKs successfully before, so I don't think I'm doing that incorrectly.

**Comment by codingatty** [comment]
This issue looks like the original error was a transient download issue. Multiple downloads yesterday yielded a small file (which turns out to be HTML text), but today the full app downloaded. However, it still will not install; the only diagnostic is "App not installed."

I am running Android 4.4.2

**Comment by pchestek** [comment]
Same problem as codingatty, Android 4.4.2.

**Comment by codingatty** [comment]
Given that the filename is `android-release-unsigned.apk`, I wonder if the PTO forgot to sign the APK.

**Comment by sashi-aeec** [comment]
I've uploaded a new apk to the same location, please try installing the new one.

**Comment by pchestek** [comment]
Yes, installed fine, thanks!

**Comment by codingatty** [comment]
Installs correctly for me as well. Thank you!
