### ISSUE TITLE
Incorrect URL in  TrademarkStatusApp/app/README.md

### ISSUE THREAD

**Issue by codingatty** [USPTO/TrademarkStatusApp#2]
The [README.md](https://github.com/USPTO/TrademarkStatusApp/blob/master/app/README.md) file uses `.releases/android-release-unsigned.apk` as the link target for the APK. That is a 404. The correct link appears to be `releases/android-release-unsigned.apk` (i.e., a link to [here](https://github.com/USPTO/TrademarkStatusApp/blob/master/app/releases/android-release-unsigned.apk)).

**Comment by sashi-aeec** [comment]
Thanks. I've merged your changes.
